//
// Generated file, do not edit! Created by nedtool 5.6 from simple.msg.
//

#ifndef __SIMPLE_M_H
#define __SIMPLE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>simple.msg:17</tt> by nedtool.
 * <pre>
 * message SimpleMsg
 * {
 *     int source;
 *     int destination;
 *     int hopCount = 0;	// TSK-MSG ONLY! [NOT USED NOW]
 *     int type;
 * }
 * </pre>
 */
class SimpleMsg : public ::omnetpp::cMessage
{
  protected:
    int source;
    int destination;
    int hopCount;
    int type;

  private:
    void copy(const SimpleMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SimpleMsg&);

  public:
    SimpleMsg(const char *name=nullptr, short kind=0);
    SimpleMsg(const SimpleMsg& other);
    virtual ~SimpleMsg();
    SimpleMsg& operator=(const SimpleMsg& other);
    virtual SimpleMsg *dup() const override {return new SimpleMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
    virtual int getType() const;
    virtual void setType(int type);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SimpleMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SimpleMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SIMPLE_M_H

